version: '3.2'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/ecommerce_api/data/

    environment:
      - POSTGRES_USER=ecommerce_api
      - POSTGRES_PASSWORD=ecommerce_api
      - POSTGRES_DB=ecommerce_api
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
