version: '3.2'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    build: 
      context: .
    restart: always
    volumes:
      - /app/backend:/vol/web
      - static-data:/vol/static 
    environment:
      - DB_ENGINE=django.db.backends.postgresql 
      - HOST=db
      - PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}
      - AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}
      - AFRICASTALKING_SENDER_ID=${AFRICASTALKING_SENDER_ID}
      - AFRICASTALKING_URL=${AFRICASTALKING_URL}
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "8080:8000"
    volumes:
      - ./proxy:/proxy  
      - /app/backend:/vol/backend
      - static-data:/vol/static

volumes:
  postgres_data:
  static-data:
